# wordpress-pv.yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi  # Debe coincidir con tu StorageClass disponible
  nfs:
    path: /mnt/wordpress  # Asegúrate de que esta ruta sea correcta
    server: 172.31.4.74  # Cambia esto por la IP de tu servidor NFS
